### ISSUE TITLE
Datatable2 Error

### ISSUE THREAD

**Issue by chhinsras** [maxim-saplin/data_table_2#101]
I just try basic datatable2. It works okay on datatable. Just add to datatable2

and I got this eror message.

`Error: Cannot hit test a render box with no size.
The hitTest() method was called on this RenderBox: RenderSemanticsAnnotations#8eade:
  needs compositing
  creator: Semantics ← _EffectiveTickerMode ← TickerMode ←
  _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#27109] ← _Theatre ←
  Overlay-[LabeledGlobalKey<OverlayState>#17ee1] ← UnmanagedRestorationScope ← _FocusMarker ← Semantics ←
  FocusScope ← AbsorbPointer ← Listener ← ⋯
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(w=1137.5, h=945.0)
  size: MISSING
Although this node is not marked as needing layout, its size is not set.
A RenderBox object must have an explicit size before it can be hit-tested. Make sure that the RenderBox
in question sets its size during layout.
    at Object.throw_ [as throw] (http://localhost:64518/dart_sdk.js:5080:11)
    at http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4458:21
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4461:26)
    at http://localhost:64518/packages/flutter/src/widgets/title.dart.lib.js:26893:42
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:7813:19)
    at overlay$._RenderTheatre.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/widgets/title.dart.lib.js:26891:28)
    at overlay$._RenderTheatre.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderAbsorbPointer.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderAbsorbPointer.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderAbsorbPointer.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:3691:68)
    at proxy_box.RenderPointerListener.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderPointerListener.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:538:26)
    at proxy_box.RenderConstrainedBox.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderConstrainedBox.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:8068:44
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:7813:19)
    at flex$.RenderFlex.new.defaultHitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:8066:30)
    at flex$.RenderFlex.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/flex.dart.lib.js:1116:19)
    at flex$.RenderFlex.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:8068:44
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:7813:19)
    at custom_layout.RenderCustomMultiChildLayoutBox.new.defaultHitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:8066:30)
    at custom_layout.RenderCustomMultiChildLayoutBox.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/custom_layout.dart.lib.js:283:19)
    at custom_layout.RenderCustomMultiChildLayoutBox.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at material._RenderInkFeatures.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at material._RenderInkFeatures.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderPhysicalModel.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderPhysicalModel.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderPhysicalModel.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:2190:20)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderRepaintBoundary.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderRepaintBoundary.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderIgnorePointer.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderIgnorePointer.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderIgnorePointer.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:3518:38)
    at http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:8068:44
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:7813:19)
    at stack.RenderStack.new.defaultHitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:8066:30)
    at stack.RenderStack.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/stack.dart.lib.js:591:19)
    at stack.RenderStack.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderDecoratedBox.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderDecoratedBox.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderFractionalTranslation.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:3076:244
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:7813:19)
    at proxy_box.RenderFractionalTranslation.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:3076:21)
    at proxy_box.RenderFractionalTranslation.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:3071:19)
    at proxy_box.RenderFractionalTranslation.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:3076:244
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:7813:19)
    at proxy_box.RenderFractionalTranslation.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:3076:21)
    at proxy_box.RenderFractionalTranslation.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:3071:19)
    at proxy_box.RenderRepaintBoundary.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderRepaintBoundary.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at routes._RenderFocusTrap.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at routes._RenderFocusTrap.new.hitTest
    (http://localhost:64518/packages/flutter/src/widgets/title.dart.lib.js:16083:26)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderOffstage.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderOffstage.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderOffstage.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:3617:38)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at http://localhost:64518/packages/flutter/src/widgets/title.dart.lib.js:26893:42
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:7813:19)
    at overlay$._RenderTheatre.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/widgets/title.dart.lib.js:26891:28)
    at overlay$._RenderTheatre.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderAbsorbPointer.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderAbsorbPointer.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderAbsorbPointer.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:3691:68)
    at proxy_box.RenderPointerListener.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderPointerListener.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:538:26)
    at http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:8068:44
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:7813:19)
    at stack.RenderStack.new.defaultHitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:8066:30)
    at stack.RenderStack.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/stack.dart.lib.js:591:19)
    at stack.RenderStack.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:64518/packages/flutter/src/rendering/proxy_box.dart.lib.js:438:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4463:18)
    at view.RenderView.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:4744:58)
    at binding$5.WidgetsFlutterBinding.new.hitTest
    (http://localhost:64518/packages/flutter/src/rendering/layer.dart.lib.js:5540:23)
    at [_handlePointerEventImmediately]
    (http://localhost:64518/packages/flutter/src/gestures/binding.dart.lib.js:312:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent
    (http://localhost:64518/packages/flutter/src/gestures/binding.dart.lib.js:305:43)
    at [_flushPointerEventQueue]
    (http://localhost:64518/packages/flutter/src/gestures/binding.dart.lib.js:295:14)
    at [_handlePointerDataPacket]
    (http://localhost:64518/packages/flutter/src/gestures/binding.dart.lib.js:286:54)
    at Object.invoke1 (http://localhost:64518/dart_sdk.js:191747:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket
    (http://localhost:64518/dart_sdk.js:171943:15)
    at [_onPointerData] (http://localhost:64518/dart_sdk.js:172879:49)
    at http://localhost:64518/dart_sdk.js:173306:26
    at http://localhost:64518/dart_sdk.js:173273:16
    at loggedHandler (http://localhost:64518/dart_sdk.js:172978:11)
      child: RenderSemanticsGestureHandler#c0664 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE`

**Comment by maxim-saplin** [comment]
Can you provide the sample repo (fit link, zip) with the bug reproducible?

**Comment by chhinsras** [comment]
i just copy the code from example

**Comment by maxim-saplin** [comment]
Please explain in detail what you do - exmples from the /example folder run just fine on my end

**Comment by chhinsras** [comment]
the code is pretty simple. If I change to Datatable. it works. 
```
return Column(
      children: [
        DataTable2(
          // columnSpacing: 0,
          // headingRowHeight: 46,
          // headingRowColor: MaterialStateProperty.resolveWith(
          //   (states) => const Color(0xFFe5e5e5),
          // ),
          // dataRowHeight: 36,
          columns: const <DataColumn2>[
            DataColumn2(
              label: Text(
                'Name',
                style: TextStyle(fontStyle: FontStyle.italic),
              ),
            ),
            DataColumn2(
              label: Text(
                'Age',
                style: TextStyle(fontStyle: FontStyle.italic),
              ),
            ),
            DataColumn2(
              label: Text(
                'Role',
                style: TextStyle(fontStyle: FontStyle.italic),
              ),
            ),
          ],
          rows: const <DataRow>[
            DataRow(
              cells: <DataCell>[
                DataCell(Text('Sarah')),
                DataCell(Text('19')),
                DataCell(Text('Student')),
              ],
            ),
            DataRow(cells: <DataCell>[
              DataCell(Text('Janine')),
              DataCell(Text('43')),
              DataCell(Text('Professor')),
            ]),
          ],
        ),
    );
}
```

**Comment by maxim-saplin** [comment]
What is on top of Column? I suspect there's a scrollable, if that's the case - DataTable2 won't work inside the scrollable. That's the whole point of the widget, it has own scrollables and having one on top defied the purpose of fixe header etc.

**Comment by chhinsras** [comment]
Right, there is SingleScrollableWidget. I removed it. and it is still same error

**Comment by maxim-saplin** [comment]
And remove Column, it also might have infinite height

**Comment by chhinsras** [comment]
right, i removed column and it works. anyway, i need to add pagination just like CV Data example. 

CV data table looks nice. would be nice if it can be use a widget like Datatable2

**Comment by maxim-saplin** [comment]
You can try PaginatedDataTable2 which has paginator implemented

**Comment by chhinsras** [comment]
I need to pass filter to server like pageSize, pageNumber

**Comment by chhinsras** [comment]
I am checking now. It would be much helpful if  you have improved documentation. its a bit lacking.
