### ISSUE TITLE
checkboxHorizontalMargin error when using the package

### ISSUE THREAD

**Issue by expertmars** [maxim-saplin/data_table_2#35]
Nothing fancy, when I am adding this import to the the project it shows this error message when compiling (even if I am not using the DataTable2 class)

`import 'package:data_table_2/data_table_2.dart';`

```
Launching lib/main.dart on Chrome in debug mode...
lib/main.dart:1
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/data_table_2-2.1.1/lib/data_table_2.dart:144:13: Error: No named parameter with the name 'checkboxHorizontalMargin'.
            checkboxHorizontalMargin: checkboxHorizontalMargin,
            ^^^^^^^^^^^^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/data_table_2-2.1.1/lib/data_table_2.dart:233:18: Error: The getter 'checkboxHorizontalMargin' isn't defined for the class 'DataTable2'.

 - 'DataTable2' is from 'package:data_table_2/data_table_2.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/data_table_2-2.1.1/lib/data_table_2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'checkboxHorizontalMargin'.
          start: checkboxHorizontalMargin ?? effectiveHorizontalMargin,

                 ^^^^^^^^^^^^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/data_table_2-2.1.1/lib/data_table_2.dart:234:17: Error: The getter 'checkboxHorizontalMargin' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/data_table_2.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/data_table_2-2.1.1/lib/data_table_2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'checkboxHorizontalMargin'.
          end: (checkboxHorizontalMargin ?? effectiveHorizontalMargin) / 2.0,
                ^^^^^^^^^^^^^^^^^^^^^^^^

Unhandled exception:
NoSuchMethodError: The getter 'fileOffset' was called on null.
Receiver: null
Tried calling: fileOffset
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ProgramCompiler._nodeStart (package:dev_compiler/src/kernel/compiler.dart:3633:30)
#2      ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1523:45)
#3      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1477:19)
#4      ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:3399:24)
#5      ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1476:15)
#6      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2235:25)
#7      ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3389:18)
#8      ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1474:16)
#9      ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:1116:38)
#10     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:657:19)
#11     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:580:21)
#12     List.forEach (dart:core-patch/growable_array.dart:403:8)
#13     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:529:23)
#14     List.forEach (dart:core-patch/growable_array.dart:403:8)
#15     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:394:15)
#16     JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:144:33)
<asynchronous suspension>
#17     FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:632:5)
<asynchronous suspension>
#18     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:545:9)
<asynchronous suspension>
#19     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1105:11)
<asynchronous suspension>

the Dart compiler exited unexpectedly.
Exited (sigterm)
Failed to compile application.

``` 

when i command + click on this file link` ../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/data_table_2-2.1.1/lib/data_table_2.dart:144:13` it show the file not exists. tried on 2 different projects and 2 different versions of data table2.

I already tried: 
```
flutter clean
flutter pub get
```
nothing is happening

**Comment by maxim-saplin** [comment]
Please run` flutter doctor` and post the output here

**Comment by expertmars** [comment]
tqacademy_admin % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by maxim-saplin** [comment]
You are using older version on Flutter (2.0.1), the most recent stable version is 2.2.3. The older version doesn't has some of the Flutter APIs the widget relies on. Please run `flutter upgrade` and all should be fine

**Comment by expertmars** [comment]
> You are using older version on Flutter (2.0.1), the most recent stable version is 2.2.3. The older version doesn't have some of the Flutter APIs the widget relies on. Please run `flutter upgrade` and all should be fine

Thank you
